### ISSUE TITLE
MaxoutLocalC01B constructor doesn't call parent constructor

### ISSUE THREAD

**Issue by TNick** [lisa-lab/pylearn2#1445]
in [here](https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/models/maxout.py#L1088).
Am I correct to assume this is a bug? Shall I make a pull request?
```python
        assert (pool_shape is None) == (pool_stride is None)
        super(MaxoutLocalC01B, self).__init__()
        
        detector_channels = num_channels * num_pieces

        self.__dict__.update(locals())
        del self.self
```

**Comment by TNick** [comment]
And while I'm at it, how about changing [this line](https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/linear/local_c01b.py#L61) from this
```python
logger.warning("partial_sum argument ignored")
```
 to this:
```python
if partial_sum is not None:
    raise NotImplementedError("partial_sum not implemented in pylearn2.linear.local_c01b.Local")
```
or to this:
```python
if partial_sum is not None:
    logger.warning("partial_sum argument ignored")
```

**Comment by lamblin** [comment]
Yes, this is a bug. A pull request would be welcome :)
Since Travis does not run on a machine with GPU, could you manually launch `nosetests` or `theano-nose` on the updated code to make sure nothing breaks?

Regarding the warning, since `partial_sum` has no effect on the numerical result (up to precision), I don't think an error is really needed.
However, I'm all for removing the warning when it is unnecessary.

**Comment by TNick** [comment]
The Travis CI build passed  on pull request #1446 
I've also run the tests with `THEANO_FLAGS='device=cpu'`
