### ISSUE TITLE
yaml_parse.py again

### ISSUE THREAD

**Issue by TNick** [lisa-lab/pylearn2#1464]
[These lines](
https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/config/yaml_parse.py#L357):
```python
construct_mapping(node)
mapping = loader.construct_mapping(node)
```
should probably be collapsed to
```python
mapping = construct_mapping(node)
```
Right?

**Comment by lamblin** [comment]
So, the first `construct_mapping` performs additional checks compared to `loader.construct_mapping`, which would let things like duplicated keys slip silently.
I think an earlier version of that code would replace `loader.construct_mapping` by `construct_mapping`, I'm not sure what changed since then. Maybe the mapping returned by both method is actually different, I'll have to investigate. If they're the same, then yes, your change makes sense.
Actually, that change may be why duplicated keys are not detected in some cases reported some time ago to the mailing list... In that case maybe we should restore [that line](https://github.com/lisa-lab/pylearn2/commit)/15affb561a320ba1e2e7fb5e1e2b1826dd8d5b95#diff-d42157694a6c922a3f6f7b6e1b20d3d0R311)

**Comment by lamblin** [comment]
@dwf Do you remember why that was changed during the integration of #705?

**Comment by TNick** [comment]
Implemented on [TNick/pyl2extra](https://github.com/TNick/pyl2extra/blob/master/pyl2extra/config/yaml_parse.py)
Closing this issue.
